### ISSUE TITLE
In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported.

### ISSUE THREAD

**Issue by radishT** [seata/seata#1568]
## Why you need it?
 首先描述我的问题：
seata 0.8.0 
eureka 作为注册中心
然后我在部署了TC node1  node2 2个节点以后，我启动我的微服务，然后关掉node1,这时候我的微服务开始不断地重连我的TC node1 ,因为eureka的服务列表中仍然显示node1+node2  这两个服务节点，所以我的微服务不断地去重连因为认定为是暂时的网络波动，直至eureka认定node1确实不是因为网络波动而是死亡以后，它才被去除出列表。这时候我的微服务才取消去重连node1的动作。

值得注意的是，这段时间持续了接近2分钟，也就是说这段时间我的微服务是不可用的。这不是我的目标，所以我希望eureka在node1挂掉的时候快速将node1移出服务列表，所以我希望配置eureka服务注册者也就是TC的instance配置：
eureka.lease.renewalInterval    // 告诉eureka多少秒检查一次我的心跳
eureka.lease.duration  // 告诉eureka在检查不到我的心跳后多少秒将我移除
我希望各配置3秒。

但是我发现！

registry.conf即使配置了这两条内容也不会生效。
![image](https://user-images.githubusercontent.com/32050371/63998456-b9a6d580-cb33-11e9-9f78-26abefa8a265.png)

无奈之下，我只能在TC的resources下添加了配置文件：eureka-client.properties
![image](https://user-images.githubusercontent.com/32050371/63998564-f8d52680-cb33-11e9-8fc0-cafc8a9d9e88.png)

后来通过阅读eureka的源码我又发现，它会从environment加载自己的配置，配置项详见
PropertyBasedInstanceConfigConstants.java 
所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的。
![image](https://user-images.githubusercontent.com/32050371/63998751-76993200-cb34-11e9-8108-ae26fdeb0cd9.png)

**Comment by radishT** [comment]
> > Hi @radishT, we detect non-English characters in the issue. This comment is an auto translation from @fescar-robot to help other users to understand this issue.
> > _**We encourage you to describe your issue in English which is more friendly to other users.**_
> 
> # In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported.
> ## Why you need it?
> First describe my problem:
> seata 0.8.0
> 
> ## How it could be?
> A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
> 
> ## Other related information
> Add any other context or screenshots about the feature request here.



> > Hi @radishT, we detect non-English characters in the issue. This comment is an auto translation from @fescar-robot to help other users to understand this issue.
> > _**We encourage you to describe your issue in English which is more friendly to other users.**_
> 
> # In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported.
> ## Why you need it?
> First describe my problem:
> seata 0.8.0
> 
> ## How it could be?
> A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.
> 
> ## Other related information
> Add any other context or screenshots about the feature request here.

**Comment by xingfudeshi** [comment]
Thanks for reporting.I will check.

**Comment by cmonkey** [comment]
如果对问题中出现的两个参数，通过对EurekaRegistryServiceImpl.getEurekaProperties 进行增强，并通过读取文件中的值进行设置，那么是实现可以的

现在的疑问是，eureka 有很多参数可以自定义，当下一次面临其它额外的参数，怎么办？

**Comment by radishT** [comment]
> 如果对问题中出现的两个参数，通过对EurekaRegistryServiceImpl.getEurekaProperties进行增强，并通过读取文件中的值进行设置，那么是实现可以的
> 
> 现在的疑问是，eureka有很多参数可以自定义，当下一次面对其他额外的参数，怎么办？

eureka会主动从environment加载配置，slievrly 表示以后会将registry config文件中的参数沉降到environment去，这样eureka就可以读取到，当然，参数名会和eureka的参数名保持一致

**Comment by cmonkey** [comment]
> > 如果对问题中出现的两个参数，通过对EurekaRegistryServiceImpl.getEurekaProperties进行增强，并通过读取文件中的值进行设置，那么是实现可以的
> > 现在的疑问是，eureka有很多参数可以自定义，当下一次面对其他额外的参数，怎么办？
> 
> eureka会主动从environment加载配置，slievrly 表示以后会将registry config文件中的参数沉降到environment去，这样eureka就可以读取到，当然，参数名会和eureka的参数名保持一致

这么说，他们内部已经设计好了，此问题就不做修改

**Comment by 852675742** [comment]
后来通过阅读eureka的源码我又发现，它会从environment加载自己的配置，配置项详见
PropertyBasedInstanceConfigConstants.java
所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的。

图片打不开，请问下加什么配置项啊？

**Comment by radishT** [comment]
> 后来通过阅读eureka的二进制我又发现，它会从环境加载自己的配置，配置项详见
> PropertyBasedInstanceConfigConstants.java
> 所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的。
> 
> 图片打不开，请问下加什么配置项啊？

就是我在问题中用到的配置项

**Comment by 852675742** [comment]
我在tc的目录conf下放了eureka-client.properties，内容为
eureka.lease.renewalInterval=1
eureka.lease.duration=2
但没有任何效果，还有其他需要配置的吗？因为您那个图片无法显示，谢谢

您说：
PropertyBasedInstanceConfigConstants.java
所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的，
启动参数是在哪里加？shell启动命令后面加吗？

**Comment by radishT** [comment]
> 我在tc的目录conf下放了eureka-client.properties，内容为
> eureka.lease.dunewalInterval = 1
> eureka.lease.duration = 2
> 但没有任何效果，还有其他需要配置的吗？因为您那个图片无法显示，谢谢
> 
> 您说：
> PropertyBasedInstanceConfigConstants.java
> 所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的，
> 启动参数是在哪里加？shell启动命令后面加吗？

maven 的 resources下添加了配置文件：eureka-client.properties  
eureka在自身的autoconfig中会去classpath下找eureka-client.properties

**Comment by radishT** [comment]
> 我在tc的目录conf下放了eureka-client.properties，内容为
> eureka.lease.dunewalInterval = 1
> eureka.lease.duration = 2
> 但没有任何效果，还有其他需要配置的吗？因为您那个图片无法显示，谢谢
> 
> 您说：
> PropertyBasedInstanceConfigConstants.java
> 所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的，
> 启动参数是在哪里加？shell启动命令后面加吗？

java启动参数  -Deureka.lease.dunewalInterval=1 -Deureka.lease.duration=2   
我测试过，这是有效的，因为会沉降到environment，其实eureka也是基于environment读取配置的

**Comment by 852675742** [comment]
好的，我验证一下，谢谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"radishT"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午2:52
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568)



 
我在tc的目录conf下放了eureka-client.properties，内容为
 eureka.lease.dunewalInterval = 1
 eureka.lease.duration = 2
 但没有任何效果，还有其他需要配置的吗？因为您那个图片无法显示，谢谢
 
您说：
 PropertyBasedInstanceConfigConstants.java
 所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的，
 启动参数是在哪里加？shell启动命令后面加吗？
  
java启动参数  -Deureka.lease.dunewalInterval=1 -Deureka.lease.duration=2
 我测试过，这是有效的，因为会沉降到environment，其实eureka也是基于environment读取配置的

**Comment by radishT** [comment]
> 好的，我验证一下，谢谢了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"radishT"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月16日(星期四) 下午2:52 收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;; 抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568) 我在tc的目录conf下放了eureka-client.properties，内容为 eureka.lease.dunewalInterval = 1 eureka.lease.duration = 2 但没有任何效果，还有其他需要配置的吗？因为您那个图片无法显示，谢谢 您说： PropertyBasedInstanceConfigConstants.java 所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的， 启动参数是在哪里加？shell启动命令后面加吗？ java启动参数 -Deureka.lease.dunewalInterval=1 -Deureka.lease.duration=2 我测试过，这是有效的，因为会沉降到environment，其实eureka也是基于environment读取配置的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我测试用的是eureka-client 1.9.12    初始化eureka配置的关键类是com.netflix.discovery.DefaultEurekaClientConfig

**Comment by 852675742** [comment]
好的，谢谢大神的指点




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"radishT"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午3:15
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568)



 
好的，我验证一下，谢谢了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"radishT"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月16日(星期四) 下午2:52 收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;; 抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568) 我在tc的目录conf下放了eureka-client.properties，内容为 eureka.lease.dunewalInterval = 1 eureka.lease.duration = 2 但没有任何效果，还有其他需要配置的吗？因为您那个图片无法显示，谢谢 您说： PropertyBasedInstanceConfigConstants.java 所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的， 启动参数是在哪里加？shell启动命令后面加吗？ java启动参数 -Deureka.lease.dunewalInterval=1 -Deureka.lease.duration=2 我测试过，这是有效的，因为会沉降到environment，其实eureka也是基于environment读取配置的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我测试用的是eureka-client 1.9.12    初始化eureka配置的关键类是com.netflix.discovery.DefaultEurekaClientConfig

**Comment by 852675742** [comment]
您好，请问下加了这2个参数，还是有10多秒-20秒这样的重试。不知道您那边会有多长时间重试？
我的微服务客户端和TC都加了eureka-client.properties的参数，内容如下：


eureka.lease.renewalInterval=1
eureka.lease.duration=2



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"radishT"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午3:15
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568)



 
好的，我验证一下，谢谢了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"radishT"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月16日(星期四) 下午2:52 收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;; 抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568) 我在tc的目录conf下放了eureka-client.properties，内容为 eureka.lease.dunewalInterval = 1 eureka.lease.duration = 2 但没有任何效果，还有其他需要配置的吗？因为您那个图片无法显示，谢谢 您说： PropertyBasedInstanceConfigConstants.java 所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的， 启动参数是在哪里加？shell启动命令后面加吗？ java启动参数 -Deureka.lease.dunewalInterval=1 -Deureka.lease.duration=2 我测试过，这是有效的，因为会沉降到environment，其实eureka也是基于environment读取配置的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我测试用的是eureka-client 1.9.12    初始化eureka配置的关键类是com.netflix.discovery.DefaultEurekaClientConfig

**Comment by radishT** [comment]
> 您好，请问下加了这2个参数，还是有10多秒-20秒这样的重试。不知道您那边会有多长时间重试？ 我的微服务客户端和TC都加了eureka-client.properties的参数，内容如下： eureka.lease.renewalInterval=1 eureka.lease.duration=2
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"radishT"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月16日(星期四) 下午3:15 收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;; 抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568) 好的，我验证一下，谢谢了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"radishT"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月16日(星期四) 下午2:52 收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;; 抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568) 我在tc的目录conf下放了eureka-client.properties，内容为 eureka.lease.dunewalInterval = 1 eureka.lease.duration = 2 但没有任何效果，还有其他需要配置的吗？因为您那个图片无法显示，谢谢 您说： PropertyBasedInstanceConfigConstants.java 所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的， 启动参数是在哪里加？shell启动命令后面加吗？ java启动参数 -Deureka.lease.dunewalInterval=1 -Deureka.lease.duration=2 我测试过，这是有效的，因为会沉降到environment，其实eureka也是基于environment读取配置的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 我测试用的是eureka-client 1.9.12 初始化eureka配置的关键类是com.netflix.discovery.DefaultEurekaClientConfig — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

视具体情况，根据项目具体的网络环境和可用性要求。如果你只有一个注册中心一个微服务，肯定策略是尽量规避网络波动造成的服务下线

**Comment by 852675742** [comment]
嗯，知道了，能控制在这么短时间内，也是可以接受的了，万分感激！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"radishT"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午4:09
收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;;
抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568)



 
您好，请问下加了这2个参数，还是有10多秒-20秒这样的重试。不知道您那边会有多长时间重试？ 我的微服务客户端和TC都加了eureka-client.properties的参数，内容如下： eureka.lease.renewalInterval=1 eureka.lease.duration=2
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"radishT"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月16日(星期四) 下午3:15 收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;; 抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568) 好的，我验证一下，谢谢了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"radishT"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月16日(星期四) 下午2:52 收件人:&nbsp;"seata/seata"<seata@noreply.github.com&gt;; 抄送:&nbsp;"张春林"<852675742@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [seata/seata] In the Seata 0.8.0 TC cluster configuration, many Eureka personalized configurations, such as daze time and heartbeat period, are not supported. (#1568) 我在tc的目录conf下放了eureka-client.properties，内容为 eureka.lease.dunewalInterval = 1 eureka.lease.duration = 2 但没有任何效果，还有其他需要配置的吗？因为您那个图片无法显示，谢谢 您说： PropertyBasedInstanceConfigConstants.java 所以我在我的启动参数中加入了我希望加入的配置项，这样是有效的， 启动参数是在哪里加？shell启动命令后面加吗？ java启动参数 -Deureka.lease.dunewalInterval=1 -Deureka.lease.duration=2 我测试过，这是有效的，因为会沉降到environment，其实eureka也是基于environment读取配置的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 我测试用的是eureka-client 1.9.12 初始化eureka配置的关键类是com.netflix.discovery.DefaultEurekaClientConfig — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
视具体情况，根据项目具体的网络环境和可用性要求。如果你只有一个注册中心一个微服务，肯定策略是尽量规避网络波动造成的服务下线
