### ISSUE TITLE
unit test failure on java 11 environment

### ISSUE THREAD

**Issue by Justice-love** [seata/seata#1702]
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
unit test class: io.seata.server.event.DefaultCoreForEventBusTest

error message:
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.042 s <<< FAILURE! - in io.seata.server.event.DefaultCoreForEventBusTest
[ERROR] test  Time elapsed: 1.041 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <1> but was: <2>
	at io.seata.server.event.DefaultCoreForEventBusTest.test(DefaultCoreForEventBusTest.java:82)
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

**Comment by cmonkey** [comment]
和jdk 版本关系不大，将@Test 替换成RepeatedTest, 并给RepeatedTest 参数1000/10000, 此异常就容易重现了

**Comment by ggndnn** [comment]
@Justice-love 
Is it based on the latest code of develop branch? Please refer to pr #1576. If so, we should consider more other reasons of this fail.

@cmonkey 
It was easy to reproduce the unit test fail after `RepeatedTest` used, because the test code did not clean objects correctly in each loop. The test case is not applicable to `RepeatedTest`. But I think it's better to release resources correctly in very test case, otherwise, there may be some unexpected situations. 

If add the code below, it's not easy to reproduce the error.

```
public void test() throws IOException, TransactionException, InterruptedException {
    ...
    SessionHolder.init(null);
    DefaultCoordinator coordinator = new DefaultCoordinator(null);
    coordinator.init();

    try {
        ...
    } finally {
        coordinator.destroy();
        SessionHolder.destory();
    }
}
```

**Comment by ggndnn** [comment]
@Justice-love ok, thank you.

**Comment by cmonkey** [comment]
通过在finally 块中调用destroy 方法，通过RepeatedTest执行100次，没有发现此异常，应该是解决掉了

**Comment by ggndnn** [comment]
Please check #1710 for more information.
