### ISSUE TITLE
整合nacos配置中心

### ISSUE THREAD

**Issue by MrLiuFang** [seata/seata#2225]
registry.conf 等其他配置 是否能整合到nacos配置中心。
在做微服务的时候不统一管理配置是个很蛋疼的事

**Comment by slievrly** [comment]
@MrLiuFang registry. conf is not integrated into the configuration center. Like the configuration center, it requires a local configuration item to specify what type the configuration center is using and what is its remote address? However, you can use .yml or .properties files instead of .conf files.
