### ISSUE TITLE
使用seata1.1,基于spring cloud,各个服务启动正常,分支事务获取不到全局事务ID,无法回滚

### ISSUE THREAD

**Issue by 414576872** [seata/seata#2550]
seata1.1,基于spring cloud,各个服务启动正常,分支事务获取不到全局事务ID

代理数据源手动设置的如下
new DataSourceProxy(masterDataSource);

application.yml的seata配置如下
seata:
  enableAutoDataSourceProxy: false
  tx-service-group: august-prod
  client:
    undo:
      data-validation: false
  service:
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      august-prod: default

事务发起方可以获取到 全局事务id
RootContext.getXID()
分支事务获取不到id,同样也无法回滚
请问是什么问题呢?

**Comment by Garlichead** [comment]
![image](https://user-images.githubusercontent.com/45086633/79231408-977e7f80-7e98-11ea-9e25-ec5befda5786.png)
see this step
ExecuteTemplate
if cannot enter two step if logic, the reason is register un success.
register step in springboot start.
such as
![image](https://user-images.githubusercontent.com/45086633/79231673-05c34200-7e99-11ea-8f75-d4c31a99269c.png)
![image](https://user-images.githubusercontent.com/45086633/79231745-1ecbf300-7e99-11ea-94ee-7385e6282dc7.png)
this step must process.

**Comment by 414576872** [comment]
已解决 是缺少依赖导致的 以下我使用的完整的seata依赖 仅供参考
`                <dependency>
			<groupId>io.seata</groupId>
			<artifactId>seata-spring-boot-starter</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-alibaba-seata</artifactId>
			<version>2.2.0.RELEASE</version>
		</dependency>`

**Comment by Garlichead** [comment]
> >

okay
