### ISSUE TITLE
【Read Committed】The global lock maintained in RM rather than TC

### ISSUE THREAD

**Issue by wjyheropk** [seata/seata#453]
如题，对于Read Committed功能，全局锁是否能本地判断，而不是去Server申请。
因为RM本地已经有undo-log了，如果undo-log没删除，说明全局事务没结束
举例：新事务先解析出会影响到的主键，再到本地undo-log中去寻找，当前有没有其他事务正在操作

**Comment by slievrly** [comment]
The existence of the undolog table does not mean that the global lock is not released, because the transaction undolog for globalCommit is asynchronously deleted. At the same time, if the primary key comparison in undolog means to resolve the blob field, because now a transaction is a row of records, the transaction may contain several primary key information.
