### ISSUE TITLE
Seata 1.5.2总是经常报Could not found global transaction xid

### ISSUE THREAD

**Issue by GreenCypress** [seata/seata#4812]
使用Dubbo3.0.9。Provider端的代码没有问题，就是不定时报这错误，奇怪的是只有部署在线上环境的时候遇到，求解。
```
### Cause: java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.6:8091:1846762744353553901, may be has finished.] ]
; uncategorized SQLException; SQL state [null]; error code [0]; io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.6:8091:1846762744353553901, may be has finished.] ]; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.6:8091:1846762744353553901, may be has finished.] ]
```

**Comment by a364176773** [comment]
官网faq

**Comment by liujunlin5168** [comment]
你好  请问一下 你应用服务接入seata后可以正常启动么，我本地应用服务启动报错（服务yaml文件没有添加seata.transport.rpcRmRequestTimeout配置）
应用服务依赖信息如下：
seata服务端版本是1.5.2，client端引用seata版本1.5.2,spring版本5.3.7.RELEASE
seata依赖如下：
<dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>1.5.2</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
            <version>2021.1</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

应用服务接入seata启动报错，错误信息如下：
APPLICATION FAILED TO START
***************************

Description:

Configuration property name 'seata.transport.rpcRmRequestTimeout' is not valid:

    Invalid characters: 'R', 'R', 'T'
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'seata.transport.rpcRmRequestTimeout' so that it conforms to the canonical names requirements.

2022-07-26 11:08:11.362 ERROR 15504 --- [           main] c.t.c.a.Slf4jFailureAnalysisReporter     : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Configuration property name 'seata.transport.rpcRmRequestTimeout' is not valid:

    Invalid characters: 'R', 'R', 'T'
    Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter

Action:

Modify 'seata.transport.rpcRmRequestTimeout' so that it conforms to the canonical names requirements.

**Comment by slievrly** [comment]
https://seata.io/zh-cn/docs/overview/faq.html

**Comment by slievrly** [comment]
> 使用Dubbo3.0.9。Provider端的代码没有问题，就是不定时报这错误，奇怪的是只有部署在线上环境的时候遇到，求解。
> 
> ```
> ### Cause: java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.6:8091:1846762744353553901, may be has finished.] ]
> ; uncategorized SQLException; SQL state [null]; error code [0]; io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.6:8091:1846762744353553901, may be has finished.] ]; nested exception is java.sql.SQLException: io.seata.core.exception.RmTransactionException: Response[ TransactionException[Could not found global transaction xid = 192.168.0.6:8091:1846762744353553901, may be has finished.] ]
> ```

https://seata.io/zh-cn/docs/overview/faq.html
