### ISSUE TITLE
服务端和客户端版本必须一致？[大家都想知道，但目前还未正式回答]

### ISSUE THREAD

**Issue by vanniuner** [seata/seata#5606]
如问题

**Comment by slievrly** [comment]
What version do you want to use? You can refer to the upgrade guide on the official website to determine the compatibility.

**Comment by vanniuner** [comment]
I just want to confirm did seata client's version need match to the server's?
e.g. I use seata-server 1.6.1 and use `io.seata:seata-core:jar:1.5.2`

**Comment by slievrly** [comment]
This is a bug discovered because the Maven transitive dependency in Dubbo caused the use of a lower version of `seata-core`. This has been fixed in the latest version. You can manually exclude `seata-core` and introduce a dependency with the same version as that of seata-spring-boot-starter.

---

这是一个发现的bug，因为dubbo 侧maven传递依赖导致了使用低版本的`seata-core`，这个在新版本已经修复。你可以手动排除`seata-core`，引入与seata-spring-boot-starter 相同版本的依赖。

**Comment by vanniuner** [comment]
Did the versions of `seata-server` and `io.seata:seata-core:jar` must euqal?
