### ISSUE TITLE
存在高危的安全漏洞Apache Kafka Connect 远程代码执行漏洞 (CVE-2023-25194)

### ISSUE THREAD

**Issue by sheng895** [seata/seata#5789]
<img width="641" alt="868e3aafdda99e649a9dd7bb4a03808" src="https://github.com/seata/seata/assets/50853359/ab470281-bb61-4857-9a4a-30b9b77c71d4">

**Comment by sheng895** [comment]
可有解决办法

**Comment by sheng895** [comment]
<img width="1044" alt="1692338506212" src="https://github.com/seata/seata/assets/50853359/c479fca4-34ad-4f43-85d5-2801de581d5d">
来自这个组件

**Comment by leizhiyuan** [comment]
the cve has fixed in Apache Kafka Connect API ([connect-api](https://mvnrepository.com/artifact/org.apache.kafka/connect-api),[connect-runtime](https://mvnrepository.com/artifact/org.apache.kafka/connect-runtime)) : 3.4.0

https://kafka.apache.org/cve-list

you can change the dep by yourself. exclude the lower version and import the high version and test it
<img width="1015" alt="image" src="https://github.com/seata/seata/assets/2684384/cc2a2fb1-356b-410a-b0bc-d0581ca6b659">

**Comment by funky-eyes** [comment]
Seata don't use kafka connects.

**Comment by leizhiyuan** [comment]
> Seata don't use kafka connects.

<img width="930" alt="image" src="https://github.com/seata/seata/assets/2684384/057a63fa-89be-4270-86b4-dcc5d52671c7">

it seems logback-kafka-appender  imported this

**Comment by leizhiyuan** [comment]
ref https://github.com/seata/seata/pull/3443

**Comment by leizhiyuan** [comment]
Perhaps we can discuss whether we still need to support this feature. The original project at https://github.com/danielwegener/logback-kafka-appender is no longer maintained.

**Comment by funky-eyes** [comment]
We can implement a kafkalogappender ourselves, it's not that difficult

**Comment by funky-eyes** [comment]
> > Seata don't use kafka connects.
> 
> <img alt="image" width="930" src="https://user-images.githubusercontent.com/2684384/277260489-057a63fa-89be-4270-86b4-dcc5d52671c7.png">
> it seems logback-kafka-appender imported this

Logappender has nothing to do with connect.

**Comment by leizhiyuan** [comment]
> Seata using kafka `send` method, not `sink` with `source`

<img width="608" alt="image" src="https://github.com/seata/seata/assets/2684384/891414a1-a4e3-4342-bacb-851f956f324c">


the title of cve is not correct, actually  is kafka-client
