### ISSUE TITLE
Fescar and spring cloud integration can not get xid problem when using Feign service call

### ISSUE THREAD

**Issue by wenchao523** [seata/seata#883]
fescar与springcloud集成时，客户端调用微服务接口时，由于hystrix 做了线程隔离 ，
Hystrix会将请求放入Hystrix的线程池中去执行，此时会新启一个子线程处理请求。
而RootContext采用threadlocal传递数据，无法在子线程中传递，造成在子线程中通过RootContext.getXid()获取为空。
    解决办法，在ThreadLocalContextCore类中，用InheritableThreadLocal 替代ThreadLocal。如下：
  public class ThreadLocalContextCore implements ContextCore {

	//private ThreadLocal<Map<String, String>> threadLocal = new ThreadLocal<Map<String, String>>()
    private ThreadLocal<Map<String, String>> threadLocal = new InheritableThreadLocal<Map<String, String>>() {
        @Override
        protected Map<String, String> initialValue() {
            return new HashMap<String, String>();
        }

    };

**Comment by CoffeeLatte007** [comment]
I don't think is's a bug. Because  in many asynchronous scenarios, There is no need for asynchronous transactions to join a distributed transaction，It makes distributed transactions larger.
In your case，I think Seata can provide some mechanism to support cross thread and let consumers choose whether to use it or not

**Comment by wangxinpier** [comment]
我也遇到了这个问题，感谢 wenchao523

**Comment by chengyan0** [comment]
hystrix 有信号量与线程池两种模式，应该只有使用线程池模式时才会出现这个问题。
